### ISSUE TITLE
test that new .zip download works on IT's machine

### ISSUE THREAD

**Issue by k-doering-NOAA** [k-doering-NOAA/backup-gdrive#1]
@iantaylor-NOAA when you have a chance could you check that the changes still work on your computer? You should expect additional .zip files that contain the source code in addition to .tar.gz files that have the bare github repositories (i.e., everything github minus the source code)

**Comment by iantaylor-NOAA** [comment]
Looks like the revised script worked but maybe the revision is not necessary now that we understand better the bare repo thing thanks to the changes in https://github.com/ropensci-org/gitcellar/pull/9.

**Comment by k-doering-NOAA** [comment]
Yeah! Do you think we should revert the changes?

**Comment by iantaylor-NOAA** [comment]
Yes, let's go ahead and revert. Part of me thinks "I don't want to go through this extra step to clone the bare repo to see the source code." But the backup should really only be used if the repo on github is lost or inaccessible, so it doesn't have to be convenient to access. We should probably go through the process at least once to make sure the files really do appear, but I think having fewer files in the backup folder seems like a good idea.

**Comment by k-doering-NOAA** [comment]
Yeah, I agree. I still haven't tested out getting the files from the bare repo, so will do that before reverting!
